### ISSUE TITLE
Tree is overwritten by new additions.

### ISSUE THREAD

**Issue by rsmith013** [cedadev/ceda-directory-tree#12]
https://github.com/cedadev/asset-scanner/issues/19

Proposed test.

add mid-level /badc/a/b/c
add high-level /badc/a
add low-level /badc/a/b/c/d

And make sure that each is a dataset with the expected attached metadata.

**Comment by Mahir-Sparkess** [comment]
Issue with `RenderTree`. The actual tree has the correct structure and metadata
